issuer: http://sso-emulator:5556

storage:
  type: memory

web:
  http: 0.0.0.0:5556
  allowedOrigins: ['*']

oauth2:
  skipApprovalScreen: true

staticClients:
  - id: example-app
    redirectURIs:
    - "http://localhost:5173/callback"
    - "http://localhost:5173"
    name: "Example App"
    public: true
    allowedOrigins:
    - "http://localhost:5173"

enablePasswordDB: true

staticPasswords:
  - email: "alice@example.com"
    preferred_username: "alice@example.com"
    hash: "$2a$10$2b2cU8CPhOTaGrs1HRQuAueS7JTT5ZHsHSzYiFPm1leZck7Mc8T4W" # password = "password"
    username: "alice"
    userID: "1001"

  - email: "bob@example.com"
    preferred_username: "bob@example.com"
    hash: "$2a$10$2b2cU8CPhOTaGrs1HRQuAueS7JTT5ZHsHSzYiFPm1leZck7Mc8T4W" # password = "password"
    username: "bob"
    userID: "1002"

  - email: "charlie@example.com"
    preferred_username: "charlie@example.com"
    hash: "$2a$10$2b2cU8CPhOTaGrs1HRQuAueS7JTT5ZHsHSzYiFPm1leZck7Mc8T4W" # password = "password"
    username: "charlie"
    userID: "1003"
