services:

  postgres_db:
    image: postgres:17.6
    restart: always
    shm_size: 128mb
    volumes:
      - pgsqlvolume:/var/lib/postgresql/data
      - ./pg_init:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: ${sqlpass}
    container_name: postgres_db
    hostname: postgres_db
    ports:
      - "5432:5432"

volumes:
  pgsqlvolume:
    driver: local
