services:
  sqlserver_db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: always
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: pass@Word
    ports:
      - "1433:1433"
    container_name: sqlserver_db
    hostname: sqlserver_db
    volumes:
      - mssqlvolume:/var/opt/mssql

  sqlserver_db_init:
    build: dbNewInit
    container_name: sqlserver_db_init
    hostname: sqlserver_db_init
    depends_on:
      - "sqlserver_db"

volumes:
  mssqlvolume:
    driver: local